version: 2.1

jobs:
  api-tests:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Prepare reports folder
          command: mkdir -p reports

      - run:
          name: Run Postman API tests
          command: npm run api:test

      - store_artifacts:
          path: reports
          destination: newman-report

workflows:
  build-and-test:
    jobs:
      - api-tests